#! /bin/sh

#### AUTOSTART ####

picom &
nm-applet&
numlockx &
conky -c $HOME/.config/bspwm/system-overview &
$HOME/.config/polybar/launch.sh &
xrdb -load $HOME/.config/.Xresources &
dunst -conf $HOME/.config/dunst/dunstrc &
feh --bg-fill --randomize $HOME/stuff/pictures/wallpapers/* &
$HOME/.config/bspwm/autostart.sh &
# Workspaces
bspc monitor -d I II III IV V

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           16
bspc config top_padding          25
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       true
#bspc config click_to_focus       true
bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"
